# Generated by Django 2.2.2 on 2021-06-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myweb1',
            name='password',
            field=models.IntegerField(max_length=50),
        ),
    ]
