# Generated by Django 2.2.2 on 2021-06-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0002_auto_20210603_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myweb1',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
