# Generated by Django 2.2.2 on 2021-06-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0003_auto_20210603_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.TextField()),
            ],
        ),
    ]
