# Generated by Django 2.2.2 on 2021-06-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0004_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
