# Generated by Django 2.2.2 on 2021-06-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0006_auto_20210612_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postslug',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
