# Generated by Django 2.2.2 on 2021-06-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0007_post_postslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(blank=True, default='2021-06-13 09:00:00.00000+5:30'),
            preserve_default=False,
        ),
    ]
