# Generated by Django 2.2.2 on 2021-06-14 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myweb1', '0009_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('about', models.TextField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
