# Generated by Django 2.2.2 on 2021-06-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0011_auto_20210614_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
