# Generated by Django 2.2.2 on 2021-06-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0013_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(default=None),
        ),
    ]
