# Generated by Django 2.2.2 on 2021-06-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0015_auto_20210614_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(default=None, null=True),
        ),
    ]
