# Generated by Django 2.2.2 on 2021-06-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0016_auto_20210614_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='', upload_to='myweb1/media'),
        ),
    ]
