# Generated by Django 2.2.2 on 2021-06-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0019_auto_20210615_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='/media/myweb1/media/download.jpg', upload_to='myweb1/media'),
        ),
    ]
