# Generated by Django 2.2.2 on 2021-06-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0022_auto_20210617_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification',
            field=models.IntegerField(blank=True, default=0, max_length=1, null=True),
        ),
    ]
