# Generated by Django 2.2.2 on 2021-06-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0024_auto_20210618_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verification',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
