# Generated by Django 2.2.2 on 2021-06-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0027_passcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcode',
            name='email',
            field=models.IntegerField(),
        ),
    ]
