# Generated by Django 2.2.2 on 2021-06-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb1', '0028_auto_20210619_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passcode',
            name='email',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='passcode',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
